#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$POSTGRES_AUTH_USER" WITH PASSWORD '$POSTGRES_AUTH_PASSWORD' CONNECTION LIMIT 100;

	CREATE DATABASE "$POSTGRES_AUTH_DB" OWNER "$POSTGRES_AUTH_USER";

  \connect "$POSTGRES_AUTH_DB";

  CREATE SCHEMA "$POSTGRES_AUTH_SCHEMA" AUTHORIZATION "$POSTGRES_AUTH_USER";

	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_AUTH_DB" TO "$POSTGRES_AUTH_USER";
EOSQL

