#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$POSTGRES_USER_USER" WITH PASSWORD '$POSTGRES_USER_PASSWORD' CONNECTION LIMIT 100;

	CREATE DATABASE "$POSTGRES_USER_DB" OWNER "$POSTGRES_USER_USER";

  \connect "$POSTGRES_USER_DB";

  CREATE SCHEMA "$POSTGRES_USER_SCHEMA" AUTHORIZATION "$POSTGRES_USER_USER";

	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_USER_DB" TO "$POSTGRES_USER_USER";
EOSQL

